import { ReactNode } from 'react'

// AppletProps is the prop object an Applet component receives. appletId and zIndex are
// generated by addApplet; height/width/x/y carry geometry; message is opaque applet data.
export type AppletProps = {
    appletId: number
    height: number
    isModal: boolean
    message: any
    width: number
    x: number
    y: number
    zIndex: number
}

// FrameProps are the props of the Frame component. The Frame has no id of its own — it
// manages its own DOM via refs and renders the headerButtons the Applet supplies. It does
// not read message.
export type FrameProps = {
    height: number
    isModal: boolean
    width: number
    x: number
    y: number
    zIndex: number
    title: string
    headerButtons: ReactNode
    children: ReactNode
}
